server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yun6
    username: root
    password: 2016900985
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.98.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.98.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


mybatis:
  type-aliases-package: com.leyou.user.pojo